name: Publish Docker Images
permissions:
  contents: write
  packages: write
on:
  workflow_call:
    inputs:
      registry-username:
        description: "Username to login to registry"
        type: string
        required: true
        default: ${{ github.actor }}

jobs:
  generate-version:
    name: Generate version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create semantic version
        id: create-semantic-version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          version_format: "v${major}.${minor}.${patch}"
          change_path: "application"
          bump_each_commit: true
    outputs:
        version: ${{ steps.create-semantic-version.outputs.version }}
        changed: ${{ steps.create-semantic-version.outputs.changed }}

  publish-docker-images:
    name: Publish
    needs: [generate-version]
    if: needs.generate-version.outputs.changed == 'true'
    strategy:
      fail-fast: true
      matrix:
        service: ["gymz-app"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish docker image
        env:
          APP_VERSION: ${{ needs.generate-version.outputs.version }}
          GH_REGISTRY_USER: ${{ inputs.registry-username }}
          GH_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew application:${{ matrix.service }}:publishImage --info
      - name: Create Tag
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token:  ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.generate-version.outputs.version }}
